### ISSUE TITLE
Open in New tab/window creates two new tabs/windows

### ISSUE THREAD

**Issue by danieltaylor** [hbang/TermHere#13]
If there is not already a tab or window open, having the new tab/window option selected causes two tabs or windows to be opened.

**Comment by nuno-azevedo** [comment]
I can confirm this, it's a little bit annoying.

**Comment by quyin** [comment]
+1. It happens here too.

**Comment by stanislavhannes** [comment]
+1

**Comment by ByteThis** [comment]
+1. One tab @ the home directory, the focused one working as intended.

**Comment by kirb** [comment]
Fixed in ef98224 for the upcoming release.

**Comment by ccasares** [comment]
still happening with 1.2.1 (9) in Mojave (10.14.2)

**Comment by hitzhangjie** [comment]
still happening with 1.2.1 (9) in Mojave (10.14.2)
