### ISSUE TITLE
Opening folder from file fails

### ISSUE THREAD

**Issue by imyelmo** [hbang/TermHere#15]
The description of TermHere says "If you select file(s), the directory that contains the file(s) will be used." but I have the following error if I have a file selected:

Last login: Thu May 11 12:28:43 on ttys001
/Users/imyelmo/Downloads/Marcas_pared.jpg
imyelmo@imyelmo-MBPR:~$ /Users/imyelmo/Downloads/Marcas_pared.jpg
-bash: /Users/imyelmo/Downloads/Marcas_pared.jpg: Permission denied
imyelmo@imyelmo-MBPR:~$

This is annoying since it is unavoidable to have some selected file while Finder is being used. I'm using last MacOS version.

**Comment by kirb** [comment]
This is controlled by the “open selected items” setting. (Admittedly this probably shouldn’t be on by default. Not sure why I made it that way.)

**Comment by imyelmo** [comment]
Thanks!!!!
