### ISSUE TITLE
Terminal “new tab” not working on High Sierra

### ISSUE THREAD

**Issue by yzlnew** [hbang/TermHere#16]
It seems that TermHere is broken on 10.13 for a while.

**Comment by kirb** [comment]
What is the issue exactly? Are you using the older version (1.1) from the App Store or unsandboxed version from [our site](https://hbang.ws/apps/termhere) (1.2.1)? There were some challenges introduced by Sierra last year that required it to be moved out of the App Store.

**Comment by yzlnew** [comment]
I'm currently using 1.2.1(9) version from site on MBP2016 with bar, macOS 10.13.1.
* click on the toolbar icon, no response
* not on the right click menu

**Comment by kirb** [comment]
What app do you have selected? Terminal & iTerm2 are the only ones currently supported on Sierra/High Sierra (update coming with a fix for others).

**Comment by yzlnew** [comment]
I'm using the default Terminal.
Also tested iTerm, which ~works fine.~ doesn't work, either.

When there's no Terminal window, it launches a new window in ~. Else, no response.

Check this [post](https://forums.macrumors.com/threads/macos-high-sierra-10-13-works-does-not-work-thread.2048660/). TermHere is currently listed as _Does Not Work_.

**Comment by kirb** [comment]
Hmm, check that System Events has accessibility permissions under Security preferences &rarr; Privacy &rarr; Accessibility. Not sure that it shows up any more (it doesn’t for me), but if you’ve disabled it before then that’d be the issue.

To confirm, try opening Script Editor.app, paste the following, and click run:

```applescript
tell application "Terminal"
	activate
	tell application "System Events"
		keystroke "t" using command down
	end tell
	do script "cd ~/Desktop" in front window
end tell
```

Should open a new tab and run the command, or show an error.

**Comment by yzlnew** [comment]
Yes, it opens a new tab in Desktop folder.

**Comment by kirb** [comment]
Ok, will look into it. I think I’ll have to try and find some other way to open a new tab without faking it by simulating cmd-t. Not sure why it’s not working in your case, but Terminal + “new tab” is the only time System Events is used and iTerm is working for you so I’m guessing the issue lies with the use of System Events. (Possibly also why App Review rejected my request to use Apple Events inside the sandbox?)

**Comment by yzlnew** [comment]
It's weird that TermHere is working for Terminal now. I don't change anything. Just switch settings and reboot.
It still opens two terminals at one time, though.

**Comment by kirb** [comment]
Interesting. I reckon System Events.app must have frozen in the background or something. I've just changed how the integration with Terminal & iTerm2 works, and that should fix the original issue and the issue of it opening two tabs.
