### ISSUE TITLE
TermHere cannot open terminal when select folder in external partion

### ISSUE THREAD

**Issue by hitzhangjie** [hbang/TermHere#18]
TermHere cannot open terminal when select folder in external partion, how to solve this problem.

It looks like permission relevant.

**Comment by kirb** [comment]
I implemented a workaround for this in the upcoming 1.3 release. (You can try it by downloading the repo and building it with Xcode — developer account not needed — but note there’s still a few bugs.)

**Comment by jonblatho** [comment]
@kirb Any word on 1.3 will actually be released? I'm running into this issue too—my entire home folder is off the system’s boot volume but on an internal SSD—so a fix would be greatly appreciated.
