### ISSUE TITLE
Always opens 2 terminal windows / tabs

### ISSUE THREAD

**Issue by tallpants** [hbang/TermHere#19]
I don't know if there's a fix for this already, but I've looked around a bit and haven't found anything.

Any time I open a terminal with TermHere (either with the right click menu or the finder toolbar button) 2 terminals open -- one at the home directory (or whatever default directory the terminal opens when it's spawned) and the other at the directory that I actually asked it to open in.

I've looked around quite a lot and can't find any way to change this, and it's driving me nuts!

**Comment by tallpants** [comment]
Nevermind, setting TermHere to reuse the last used tab fixed it. Literally 10 seconds after creating the issue. I deserve a medal.

**Comment by kirb** [comment]
Duplicate of #13 which I’ve fixed for the upcoming release.
