### ISSUE TITLE
One-click toolbar button

### ISSUE THREAD

**Issue by fregante** [hbang/TermHere#4]
I'll probably never need to open the settings, especially contextually to a Finder window. It'd be best if this was a one-click button to open Terminal

<img width="172" alt="screen shot 2016-07-25 at 18 19 00" src="https://cloud.githubusercontent.com/assets/1402241/17099717/ed1d5240-521e-11e6-913a-f18c0c73ed4b.png">

**Comment by kirb** [comment]
This is already implemented for a future release: #2. It was a menu because that’s what the API expects; now we trick it by performing the action when Finder asks us for our menu. (This does mean the dropdown arrow is still there. Can’t fix that.)

**Comment by ErikSwan** [comment]
Is this implemented in v1.1 on the Mac App Store? I'm still seeing the dropdown menu.

**Comment by kirb** [comment]
@ErikSwan, unfortunately no; haven’t released it yet. If you have Xcode you can download this repo and build it for yourself (Apple developer account not needed).
