### ISSUE TITLE
Sierra Support

### ISSUE THREAD

**Issue by erikng** [hbang/TermHere#9]
Looks like it no longer works after upgrading. Confirmed the extension is still enabled.

**Comment by iAdam1n** [comment]
We're aware of this.

**Comment by kirb** [comment]
I'm a bit behind right now but still expect to have TermHere 1.2 submitted to Apple shortly. A few features need finishing first. (Not sure how long it will take Apple to review/approve considering Sierra just came out.)

**Comment by funkenstrahlen** [comment]
I also just discovered this bug. Happy to see your are already working on a fix. Thanks a lot :)

**Comment by RudyB** [comment]
What is the status of the update?

**Comment by iAdam1n** [comment]
Hi @RudyBermudez, details on the update can be found at https://www.reddit.com/r/hbang/comments/54fbor/termhere_12/.

**Comment by kirb** [comment]
Arg I didn’t link the release post here – sorry! It’s… [not quite going too well](https://www.reddit.com/r/hbang/comments/54fbor/termhere_12/). App Review doesn’t agree with the method I’ve changed to using in order to support Sierra (and to add more features), and is pushing me onto their paid developer support service rather than just suggesting a supported alternative. I’m lost on what I should do here; TermHere sits very close to the limits of the sandbox, so moving outside of the App Store would remove a heap of stress/uncertainty when releasing updates but adds the stress/inconvenience of getting people onto the new app.

**Comment by erikng** [comment]
I would say that most people using this application are power users and would have no difficulty moving to a non Mac App Store version.

Is the fear getting the message? If so, maybe remove this feature and put a message inside the App Store version explaining that you can't enable the feature and to look at your website for more information.

It would require forking your code but only this one time.

I wouldn't use their developer service either. You will just pay to get a "No".

On Oct 18, 2016, at 2:09 AM, Adam Demasi <notifications@github.com<mailto:notifications@github.com>> wrote:

Arg I didn't link the release post here - sorry! It's... not quite going too wellhttps://www.reddit.com/r/hbang/comments/54fbor/termhere_12/. App Review doesn't agree with the method I've changed to using in order to support Sierra (and to add more features), and is pushing me onto their paid developer support service rather than just suggesting a supported alternative. I'm lost on what I should do here; TermHere sits very close to the limits of the sandbox, so moving outside of the App Store would remove a heap of stress/uncertainty when releasing updates but adds the stress/inconvenience of getting people onto the new app.

##

**Comment by RudyB** [comment]
I agree with @erikng . I would not mind a non-app store release at all. Honestly whatever gets the fix in my hands the fastest. Adding an automatic update feature would not be that difficult to implement. You could even self-host the application download on github. 

You would just have to update the mac application with a message saying that it is deprecated and to the version hosted here.

**Comment by liufsd** [comment]
i wonder that if you use this key ,the apple review will not pass.as i know apple do not allow this key.

com.apple.security.temporary-exception.apple-events

**Comment by liufsd** [comment]
but i do not know why "go2shell" in app store

**Comment by kirb** [comment]
That’s exactly what I used/what Apple disagreed with. https://github.com/hbang/TermHere/blob/master/TermHere/TermHere.entitlements

**Comment by liufsd** [comment]
Yeah, i have also trouble with this.and even i have found this http://stackoverflow.com/questions/12858642/mac-app-rejection-temporary-exception-entitlement-key-for-safari
https://forum.xojo.com/24364-how-can-you-determine-what-entitlements-an-app-is-using/0
but also rejection.

**Comment by liufsd** [comment]
If you got solution,please tell me.thanks.

**Comment by liufsd** [comment]
hi~ why this app (https://itunes.apple.com/cn/app/termhere/id1114363220?mt=12&ign-mpt=uo%3D4) can submit on app store?  but not working on 10.12~ So i have question: if you set this https://github.com/hbang/TermHere/blob/master/TermHere/TermHere.entitlements , the app not allow you to this . how did you submit it to store?

**Comment by liufsd** [comment]
@kirb  Do you fix this ??? The apple allow you to do this or not now ???

**Comment by kirb** [comment]
The version we just released on [our website](https://hbang.ws/apps/termhere/) is not sandboxed and works with Sierra.

**Comment by liufsd** [comment]
@kirb aha this is a good news~ and also bad news for apple~

**Comment by erikng** [comment]
FYI but https://hbang.com.au/termhere Still points to App Store.

**Comment by kirb** [comment]
Ah good catch @erikng, knew I missed something in all the effort to release this. Redirects to the hbang.ws page now.
